name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  format-pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install pylint
      run: |
        pip install -e .
        pip install pylint
    - name: Run pylint
      run: |
        pylint --rcfile=pylint.conf flaskr > pylint.txt
    - name: Upload pylint results
      uses: actions/upload-artifact@v3
      with:
          name: pylint-results
          path: pylint.txt

  secret-scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Scan for secrets with bandit
        run: |
          pip install bandit
          bandit -r ./flaskr -f json -o bandit.json
      - name: Upload bandit results
        uses: actions/upload-artifact@v3
        with:
            name: bandit-results
            path: bandit.json

  deploy:
    needs:
      - dast
      - sast
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./Environment/App/app/
          file: ./Environment/App/app/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: e0260226/tic4302demo:latest
  
  container-scan:
    needs:
      - deploy
    runs-on: ubuntu-latest
    steps:
      - name: Run Dockle
        uses: erzz/dockle-action@v1.1.1
        with:
          image: e0260226/tic4302demo
          report-format: json
          report-name: dockle-report
      - name: Upload Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Dockle Report
          path: dockle-report.json