name: CI
on:
  push:
    branches:
      - main
jobs:
  secret-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          mkdir -p logs/
          echo 'flaskr' > logs/exclude.txt
      - uses: max/secret-scan@master
        with:
          exclude_path: logs/exclude.txt
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker-compose
        run: docker-compose -f ./Environment/App/docker-compose.yml up --build -d
  sca: