name: Test 2

on:
  push:
    branches:
      - main

jobs:
  format-pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install pylint
      run: |
        pip install -e .
        pip install pylint
    - name: Run pylint
      run: |
        pylint --rcfile=pylint.conf flaskr > pylint.txt

    - name: Upload pylint results
      uses: actions/upload-artifact@v3
      with:
          name: pylint-results
          path: pylint.txt
